android: gallium/softpipe: Depend on nir
    In file included from external/mesa3d/src/gallium/drivers/softpipe/sp_screen.c:29:
    external/mesa3d/src/compiler/nir/nir.h:53:10: fatal error: 'nir_opcodes.h' file not found
    #include "nir_opcodes.h"
             ^~~~~~~~~~~~~~~